server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:password}
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-checksums: true

  main:
    banner-mode: off


logging:
  level:
    #    org.zalando.logbook: TRACE
    ru.yandex.practicum: TRACE
