server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:password}
  sql:
    init:
      mode: always

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    clear-checksums: true

logging:
  level:
    ru.yandex.practicum: WARN
