CREATE TABLE IF NOT EXISTS directors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors (
    film_id  BIGINT NOT NULL,
    director_id BIGINT NOT NULL,
    PRIMARY KEY (film_id, director_id)
);

ALTER TABLE film_directors
    ADD FOREIGN KEY (film_id) REFERENCES films(id) ON DELETE CASCADE;

ALTER TABLE film_directors
    ADD FOREIGN KEY (director_id) REFERENCES directors(id) ON DELETE CASCADE;